### GET hello
GET http://localhost:8888/hello

### GET info
GET http://localhost:8888/info

### GET h
GET http://localhost:8888/g

### POST user
POST http://localhost:8888/ga/cn.kimmking.kkrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.kimmking.kkrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}



