### GET hello
GET http://localhost:8888/hello

### GET gw 1
GET http://localhost:8888/gw/aaa



### POST kkrpc
POST http://localhost:8888/gw/kkrpc/cn.kimmking.kkrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.kimmking.kkrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST direct
POST http://localhost:8888/gw/direct/cn.kimmking.kkrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"cn.kimmking.kkrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST direct backend
POST http://localhost:8888/gw/direct/cn.kimmking.kkrpc.demo.api.UserService?backend=http://localhost:8081/kkrpc
Content-Type: application/json

{
  "service":"cn.kimmking.kkrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}
